[tox]
envlist =
       {py310}-{django51,django52}
       {py311}-{django51,django52}
       {py312}-{django51,django52,django6,django61}
       {py313}-{django51,django52,django6,django61}
       {py314}-{django52,django6,django61}

[testenv]
runner = uv-venv-lock-runner
commands =
        django51: uv pip install Django>=5.1,<5.2
        django52: uv pip install Django>=5.2,<6.0
        django6: uv pip install Django>=6.0,<6.1
        django61: uv pip install Django>=6.1,<6.2
        pytest -W error::DeprecationWarning -W error::PendingDeprecationWarning {posargs}  --cov genfkadmin --cov-branch --cov-report term-missing --cov-fail-under 90
envdir = {toxworkdir}/venvs/{envname}
allowlist_externals = pytest
